#!/bin/bash

set -o allexport ; source .env ; set +o allexport
database_name=$(echo $DATABASE_URL | grep -Eo '[a-z_-]+$')
if psql $DATABASE_URL -c 'SELECT 1;' > /dev/null 2>&1 ; then
  dropdb "$database_name"
  echo "Dropping '$database_name'"
else
  echo "Database '$database_name' does not exist"
fi
